stages:
    - test
    - deploy

lint:
    stage: test
    image: rust
    before_script:
        - rustup component add clippy
        - cargo build -v
    script:
        - cargo clippy -v

deploy:
    stage: deploy
    image: rust
    before_script:
        - apt update
        - apt install -y mingw-w64
    script:
        - ./ci/release.sh
