stages:
    - test
    - deploy

lint:clippy:
    stage: test
    image: rustlang/rust:nightly
    before_script:
        - rustup update
        - rustup component add clippy
        - cargo build -v
    script:
        - cargo clippy -- -D warnings
    allow_failure: true

lint:fmt:
    stage: test
    image: rustlang/rust:nightly
    before_script:
        - rustup component add rustfmt
    script:
        - cargo fmt -- --all
    allow_failure: true

deploy:
    stage: deploy
    image: rustlang/rust:nightly
    before_script:
        - apt update
        - apt install -y mingw-w64
        - rustup target add x86_64-pc-windows-gnu
    script:
        - ./ci/release.sh
        - ls build

cache:
    paths:
        - target/
