[package]
name = "valala"
version = "0.1.0"
authors = ["Abel <abelcd@protonmail.com>"]
edition = "2018"

[dependencies]
glium = "0.25.0"
image = "0.21.2"
cgmath = "0.17.0"
obj-rs = { version = "0.5", features = ["glium-support"] }
clap = "2.33.0"
rand = "0.6.5"
